modLoader = "javafml"
loaderVersion = "[47,)"
license = "MIT"
issueTrackerURL = "https://github.com/yourname/valkyrien_steampunk/issues"

[[mods]]
modId = "valkyrien_steampunk"
version = "1.0.0"
displayName = "Valkyrien Steampunk"
displayURL = "https://github.com/yourname/valkyrien_steampunk"
authors = ["yourname"]
description = '''
Adds rope constraints and steampunk-themed content using Valkyrien Skies 2.
'''
logoFile = "icon.png"

[[dependencies.valkyrien_steampunk]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.valkyrien_steampunk]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.valkyrien_steampunk]]
modId = "valkyrienskies"
mandatory = true
versionRange = "2.5.0-beta.3+980ca5f0e5" # Replace with your actual VS2 version range
ordering = "AFTER"
side = "BOTH"
